In [5]:
import numpy as np

# 你的 .npz 文件路径
npz_path = "/Volumes/data_files/LDGM/example/height/ldgm_npz/1kg_ldgm.AFR.npz"

# 加载文件
data = np.load(npz_path, allow_pickle=True)

# 查看里面包含哪些数组
print("包含的字段：", list(data.keys()))

# 查看各字段的基本信息
print("\npositions:", data['positions'][:10])
print("diagonals:", data['diagonals'][:10])
print("neighbors:", data['neighbors'][:3])
print("weights:", data['weights'][:3])

包含的字段： ['positions', 'diagonals', 'neighbors', 'weights']

positions: [16141 16280 16474 16576 16719 16825 16856 16949 17005 17020]
diagonals: [1.       1.147787 1.03214  1.011848 1.       1.089219 1.       2.189416
 1.       2.454739]
neighbors: [array([], dtype=int32) array([ 28, 198], dtype=int32)
 array([ 6979, 10314, 11394], dtype=int32)]
weights: [array([], dtype=float32) array([-0.394797, -0.104057], dtype=float32)
 array([-0.108348, -0.093365, -0.102177], dtype=float32)]


In [6]:
data

NpzFile '/Volumes/data_files/LDGM/example/height/ldgm_npz/1kg_ldgm.AFR.npz' with keys: positions, diagonals, neighbors, weights

In [5]:
import numpy as np

def load_ldgm_edge_list(npz_path):
    """
        positions (np.ndarray): positions 列表（与 index 一一对应）
        diagonals (np.ndarray): 每个 SNP 的对角线权重
        neighbors (list of np.ndarray): 每个 SNP 的邻居节点索引
        weights (list of np.ndarray): 每个 SNP 的邻边权重（与 neighbors 对应）
    """
    npz = np.load(npz_path, allow_pickle=True)

    snp_list = npz['positions']
    diagonal = npz['diagonals']
    neighbors = npz['neighbors']
    weights = npz['weights']

    return snp_list, diagonal, neighbors, weights

positions, diagonal, neighbors, weights = load_ldgm_edge_list('/Volumes/data_files/LDGM/example/height/ldgm_npz/1kg_ldgm.EUR.npz')

In [7]:
neighbors

array([array([ 6, 12, 21, 52], dtype=int32), array([12], dtype=int32),
       array([], dtype=int32), ..., array([], dtype=int32),
       array([], dtype=int32), array([], dtype=int32)], dtype=object)

In [8]:
positions

array([   16719,    16841,    16856, ..., 50791885, 50791894, 50792792],
      dtype=int32)

In [9]:
weights

array([array([-0.319217, -0.466229, -0.066764, -0.247807], dtype=float32),
       array([-0.914626], dtype=float32), array([], dtype=float32), ...,
       array([], dtype=float32), array([], dtype=float32),
       array([], dtype=float32)], dtype=object)